# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c6415b1d4f23a35753af4ed4aba9a84db96a001eb29b1c20eefc70458b7be54d7dec5a1a83526ef91fac2b77f6e7e2213370f6c472f2a49829026aadcb2e83bb

test:
  secret_key_base: 20886c5afbde4bb38ec86f3f5861ce4422af5ebfe65bafc13c86d1da0005331c4f3c19f61c1d3b5e3507049d4dbab6240dc59e9bc76fab84528e6c04ca4bb23c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
